FROM golang:1.25-alpine3.22 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/monocron-runner ./cmd/monocron-runner

FROM alpine:3.22
WORKDIR /app
COPY --from=builder /out/monocron-runner .
CMD ["./monocron-runner"]
