// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertLog = `-- name: InsertLog :one
INSERT INTO logs (
    run_id,
    log_line,
    logged_at
)
VALUES ($1, $2, NOW())
RETURNING id, run_id, log_line, logged_at
`

type InsertLogParams struct {
	RunID   uuid.UUID `json:"run_id"`
	LogLine string    `json:"log_line"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, insertLog, arg.RunID, arg.LogLine)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LogLine,
		&i.LoggedAt,
	)
	return i, err
}

const listLogsByRun = `-- name: ListLogsByRun :many
SELECT id, run_id, log_line, logged_at FROM logs
WHERE run_id = $1
ORDER BY logged_at ASC
`

func (q *Queries) ListLogsByRun(ctx context.Context, runID uuid.UUID) ([]Log, error) {
	rows, err := q.db.Query(ctx, listLogsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LogLine,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
