// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID       uuid.UUID          `json:"id"`
	RunID    uuid.UUID          `json:"run_id"`
	LogLine  string             `json:"log_line"`
	LoggedAt pgtype.Timestamptz `json:"logged_at"`
}

type Run struct {
	ID          uuid.UUID          `json:"id"`
	TaskID      uuid.UUID          `json:"task_id"`
	ScheduledAt time.Time          `json:"scheduled_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	Status      string             `json:"status"`
	Source      string             `json:"source"`
	Logs        []byte             `json:"logs"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Schedule          string             `json:"schedule"`
	Timezone          string             `json:"timezone"`
	ConcurrencyPolicy string             `json:"concurrency_policy"`
	Retries           int                `json:"retries"`
	Backoff           *string            `json:"backoff"`
	Catchup           bool               `json:"catchup"`
	CatchupWindow     time.Duration      `json:"catchup_window"`
	Executor          []byte             `json:"executor"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
