// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const enqueueRun = `-- name: EnqueueRun :one
INSERT INTO runs (
    task_id,
    scheduled_at,
    status,
    source,
    created_at
)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, task_id, scheduled_at, started_at, finished_at, status, source, logs, created_at
`

type EnqueueRunParams struct {
	TaskID      uuid.UUID `json:"task_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
	Status      string    `json:"status"`
	Source      string    `json:"source"`
}

func (q *Queries) EnqueueRun(ctx context.Context, arg EnqueueRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, enqueueRun,
		arg.TaskID,
		arg.ScheduledAt,
		arg.Status,
		arg.Source,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Source,
		&i.Logs,
		&i.CreatedAt,
	)
	return i, err
}

const getDueRuns = `-- name: GetDueRuns :many
SELECT id, task_id, scheduled_at, started_at, finished_at, status, source, logs, created_at FROM runs
WHERE status = 'QUEUED'
  AND scheduled_at <= NOW()
ORDER BY scheduled_at ASC
`

func (q *Queries) GetDueRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.Query(ctx, getDueRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Source,
			&i.Logs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastScheduledForTask = `-- name: GetLastScheduledForTask :one
SELECT scheduled_at
FROM runs
WHERE task_id = $1
ORDER BY scheduled_at DESC
LIMIT 1
`

func (q *Queries) GetLastScheduledForTask(ctx context.Context, taskID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLastScheduledForTask, taskID)
	var scheduled_at time.Time
	err := row.Scan(&scheduled_at)
	return scheduled_at, err
}

const listPendingRuns = `-- name: ListPendingRuns :many
SELECT id, task_id, scheduled_at, started_at, finished_at, status, source, logs, created_at FROM runs
WHERE status = 'QUEUED'
ORDER BY scheduled_at ASC
`

func (q *Queries) ListPendingRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.Query(ctx, listPendingRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Source,
			&i.Logs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRuns = `-- name: ListRecentRuns :many
SELECT r.id, r.task_id, t.name AS task_name, r.scheduled_at, r.status, r.source
FROM runs r
JOIN tasks t ON t.id = r.task_id
ORDER BY r.scheduled_at DESC
LIMIT $1
`

type ListRecentRunsRow struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"task_id"`
	TaskName    string    `json:"task_name"`
	ScheduledAt time.Time `json:"scheduled_at"`
	Status      string    `json:"status"`
	Source      string    `json:"source"`
}

func (q *Queries) ListRecentRuns(ctx context.Context, limit int32) ([]ListRecentRunsRow, error) {
	rows, err := q.db.Query(ctx, listRecentRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentRunsRow
	for rows.Next() {
		var i ListRecentRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskName,
			&i.ScheduledAt,
			&i.Status,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByStatus = `-- name: ListRunsByStatus :many
SELECT r.id, r.task_id, t.name AS task_name, r.scheduled_at, r.status, r.source
FROM runs r
JOIN tasks t ON t.id = r.task_id
WHERE r.status = $1
ORDER BY r.scheduled_at DESC
LIMIT $2
`

type ListRunsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

type ListRunsByStatusRow struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"task_id"`
	TaskName    string    `json:"task_name"`
	ScheduledAt time.Time `json:"scheduled_at"`
	Status      string    `json:"status"`
	Source      string    `json:"source"`
}

func (q *Queries) ListRunsByStatus(ctx context.Context, arg ListRunsByStatusParams) ([]ListRunsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listRunsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByStatusRow
	for rows.Next() {
		var i ListRunsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskName,
			&i.ScheduledAt,
			&i.Status,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsRunning = `-- name: MarkAsRunning :exec
UPDATE runs
SET status = 'RUNNING'
WHERE id = $1 AND status = 'QUEUED'
`

func (q *Queries) MarkAsRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAsRunning, id)
	return err
}

const markRunCompleted = `-- name: MarkRunCompleted :exec
UPDATE runs
SET status = 'COMPLETED',
    finished_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRunCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRunCompleted, id)
	return err
}

const markRunFailed = `-- name: MarkRunFailed :exec
UPDATE runs
SET status = 'FAILED',
    finished_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRunFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRunFailed, id)
	return err
}
