// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"time"
)

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE name = $1
`

func (q *Queries) DeleteTask(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteTask, name)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, name, schedule, timezone, concurrency_policy, retries, backoff, catchup, catchup_window, executor, created_at, updated_at FROM tasks
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, name string) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, name)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.Timezone,
		&i.ConcurrencyPolicy,
		&i.Retries,
		&i.Backoff,
		&i.Catchup,
		&i.CatchupWindow,
		&i.Executor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, name, schedule, timezone, concurrency_policy, retries, backoff, catchup, catchup_window, executor, created_at, updated_at FROM tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTaskById(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.Timezone,
		&i.ConcurrencyPolicy,
		&i.Retries,
		&i.Backoff,
		&i.Catchup,
		&i.CatchupWindow,
		&i.Executor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, schedule, timezone, concurrency_policy, retries, backoff, catchup, catchup_window, executor, created_at, updated_at FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Schedule,
			&i.Timezone,
			&i.ConcurrencyPolicy,
			&i.Retries,
			&i.Backoff,
			&i.Catchup,
			&i.CatchupWindow,
			&i.Executor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTask = `-- name: UpsertTask :one
INSERT INTO tasks (
    name,
    schedule,
    timezone,
    concurrency_policy,
    retries,
    backoff,
    catchup,
    catchup_window,
    executor,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
ON CONFLICT (name) DO UPDATE
SET
    schedule           = EXCLUDED.schedule,
    timezone           = EXCLUDED.timezone,
    concurrency_policy = EXCLUDED.concurrency_policy,
    retries            = EXCLUDED.retries,
    backoff            = EXCLUDED.backoff,
    catchup            = EXCLUDED.catchup,
    catchup_window     = EXCLUDED.catchup_window,
    executor           = EXCLUDED.executor,
    updated_at         = NOW()
RETURNING id, name, schedule, timezone, concurrency_policy, retries, backoff, catchup, catchup_window, executor, created_at, updated_at
`

type UpsertTaskParams struct {
	Name              string        `json:"name"`
	Schedule          string        `json:"schedule"`
	Timezone          string        `json:"timezone"`
	ConcurrencyPolicy string        `json:"concurrency_policy"`
	Retries           int           `json:"retries"`
	Backoff           *string       `json:"backoff"`
	Catchup           bool          `json:"catchup"`
	CatchupWindow     time.Duration `json:"catchup_window"`
	Executor          []byte        `json:"executor"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, upsertTask,
		arg.Name,
		arg.Schedule,
		arg.Timezone,
		arg.ConcurrencyPolicy,
		arg.Retries,
		arg.Backoff,
		arg.Catchup,
		arg.CatchupWindow,
		arg.Executor,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.Timezone,
		&i.ConcurrencyPolicy,
		&i.Retries,
		&i.Backoff,
		&i.Catchup,
		&i.CatchupWindow,
		&i.Executor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
