// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addJob = `-- name: AddJob :one
INSERT INTO jobs (id, entry_id, name, status, cron_spec, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entry_id, name, status, cron_spec, scheduled_at, created_at, updated_at
`

type AddJobParams struct {
	ID          uuid.UUID `json:"id"`
	EntryID     int       `json:"entry_id"`
	Name        string    `json:"name"`
	Status      string    `json:"status"`
	CronSpec    string    `json:"cron_spec"`
	ScheduledAt time.Time `json:"scheduled_at"`
}

func (q *Queries) AddJob(ctx context.Context, arg AddJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, addJob,
		arg.ID,
		arg.EntryID,
		arg.Name,
		arg.Status,
		arg.CronSpec,
		arg.ScheduledAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Name,
		&i.Status,
		&i.CronSpec,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, entry_id, name, status, cron_spec, scheduled_at, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Name,
		&i.Status,
		&i.CronSpec,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, entry_id, name, status, cron_spec, scheduled_at, created_at, updated_at
FROM jobs
ORDER BY scheduled_at ASC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Name,
			&i.Status,
			&i.CronSpec,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET
  entry_id     = COALESCE($2, entry_id),
  name         = COALESCE($3,     name),
  status       = COALESCE($4,   status),
  cron_spec    = COALESCE($5,cron_spec),
  scheduled_at = COALESCE($6, scheduled_at)
WHERE id = $1
RETURNING id, entry_id, name, status, cron_spec, scheduled_at, created_at, updated_at
`

type UpdateJobParams struct {
	ID          uuid.UUID          `json:"id"`
	EntryID     int                `json:"entry_id"`
	Name        *string            `json:"name"`
	Status      *string            `json:"status"`
	CronSpec    *string            `json:"cron_spec"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.EntryID,
		arg.Name,
		arg.Status,
		arg.CronSpec,
		arg.ScheduledAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Name,
		&i.Status,
		&i.CronSpec,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobEntryAndNext = `-- name: UpdateJobEntryAndNext :one
UPDATE jobs
SET entry_id = $2, scheduled_at = $3
WHERE id = $1
RETURNING id, entry_id, name, status, cron_spec, scheduled_at, created_at, updated_at
`

type UpdateJobEntryAndNextParams struct {
	ID          uuid.UUID `json:"id"`
	EntryID     int       `json:"entry_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
}

func (q *Queries) UpdateJobEntryAndNext(ctx context.Context, arg UpdateJobEntryAndNextParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobEntryAndNext, arg.ID, arg.EntryID, arg.ScheduledAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Name,
		&i.Status,
		&i.CronSpec,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2
WHERE id = $1
RETURNING id, entry_id, name, status, cron_spec, scheduled_at, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Name,
		&i.Status,
		&i.CronSpec,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
